# Generated by Django 5.0.6 on 2025-03-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the exercise', max_length=100, unique=True)),
                ('activity', models.CharField(choices=[('Strength', 'Strength Training'), ('Cardio', 'Cardiovascular'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance')], help_text='Primary activity category', max_length=50)),
                ('type', models.CharField(choices=[('Barbell', 'Barbell'), ('Dumbbell', 'Dumbbell'), ('Machine', 'Machine'), ('Bodyweight', 'Bodyweight'), ('Kettlebell', 'Kettlebell'), ('Resistance Band', 'Resistance Band'), ('Other', 'Other')], help_text='Type of equipment or method used', max_length=50)),
                ('muscle_group', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Legs', 'Legs'), ('Abs', 'Abdominals'), ('Full Body', 'Full Body')], help_text='Main muscle group targeted', max_length=50)),
                ('sub_group', models.CharField(blank=True, choices=[('Upper Chest', 'Upper Chest'), ('Lower Chest', 'Lower Chest'), ('Lats', 'Latissimus Dorsi'), ('Traps', 'Trapezius'), ('Quads', 'Quadriceps'), ('Hamstrings', 'Hamstrings'), ('Calves', 'Calves'), ('Glutes', 'Glutes')], help_text='Specific sub-muscle group targeted (optional)', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['name'],
            },
        ),
    ]
