# Generated by Django 5.0.6 on 2025-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Abs', 'Abdominals'), ('Full Body', 'Full Body')], help_text='Main muscle group targeted', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sub_group',
            field=models.CharField(blank=True, choices=[('Upper Chest', 'Upper Chest'), ('Lower Chest', 'Lower Chest'), ('Lats', 'Latissimus Dorsi'), ('Traps', 'Trapezius'), ('Quads', 'Quadriceps'), ('Hamstrings', 'Hamstrings'), ('Calves', 'Calves'), ('Glutes', 'Glutes'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps')], help_text='Specific sub-muscle group targeted (optional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Barbell', 'Barbell'), ('Dumbbell', 'Dumbbell'), ('Machine', 'Machine'), ('Bodyweight', 'Bodyweight'), ('Kettlebell', 'Kettlebell'), ('Resistance Band', 'Resistance Band'), ('Run', 'Running'), ('Other', 'Other')], help_text='Type of equipment or method used', max_length=50),
        ),
    ]
