# Generated by Django 5.0.6 on 2025-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_exercise_muscle_group_alter_exercise_sub_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the routine', max_length=100, unique=True)),
                ('exercises', models.ManyToManyField(help_text='Exercises included in this routine', related_name='routines', to='api.exercise')),
            ],
            options={
                'verbose_name': 'Routine',
                'verbose_name_plural': 'Routines',
                'ordering': ['name'],
            },
        ),
    ]
