# Generated by Django 5.0.6 on 2025-04-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exerciselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='training_points',
            field=models.PositiveIntegerField(default=1, help_text='Points assigned to this exercise for training load calculation'),
        ),
    ]
