# Generated by Django 5.0.6 on 2025-04-02 11:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_exercise_training_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDownWeeklyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='The year for which the target is set')),
                ('week', models.PositiveIntegerField(help_text='The week number (ISO 8601) for which the target is set')),
                ('target_points', models.PositiveIntegerField(default=50, help_text='The target training points for the week', validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Top-Down Weekly Target',
                'verbose_name_plural': 'Top-Down Weekly Targets',
                'ordering': ['year', 'week'],
                'unique_together': {('user', 'year', 'week')},
            },
        ),
    ]
