# Generated by Django 5.0.6 on 2026-05-17 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_topdownweeklytarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField(help_text='ISO 8601 week number')),
                ('content', models.JSONField(help_text='Structured analysis: summary, observations, suggestions')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Analysis',
                'verbose_name_plural': 'Weekly Analyses',
                'ordering': ['-year', '-week'],
                'unique_together': {('user', 'year', 'week')},
            },
        ),
    ]
